// Copy the files the React build does not own into dist: the interactive tool
// pages, the Idea Lab subsystem, the shared assets those need, and the SEO and
// meta files. React owns the converted routes; everything here is served as-is.
import { cpSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DIST = join(ROOT, "dist");

// Directories copied wholesale (path preserved).
const DIRS = [
  "assets",
  "education/assets",
  "images",
  "idea-lab",
  "reviews",
  "docs",
  ".well-known"
];

// The interactive calculator/reference pages that stay static.
const TOOLS = ["calibration", "scaling", "square-root", "rtd", "thermocouple", "formulas", "numbering-systems"];

// Root-level SEO and meta files.
// 404.html and sitemap.xml are generated by the prerender/sitemap steps;
// favicons live under images/.
const FILES = [
  "CNAME", "robots.txt", "llms.txt", "manifest.webmanifest",
  "LICENSES.md", "README.md"
];

// The IndexNow key file has a hashed name; pick it up if present.
const KEYFILE = "1f584735acada06d91ae55170c059c23.txt";

const skipMarkdownInIdeaLab = (src) =>
  !(src.includes(`idea-lab`) && (src.endsWith("CONTENT_PACK.md") || src.endsWith("CURRICULUM.md") || src.endsWith("IDEA_LAB_DESIGN.md")));

let n = 0;
function copy(rel, filter) {
  const from = join(ROOT, rel);
  if (!existsSync(from)) return;
  cpSync(from, join(DIST, rel), { recursive: true, filter });
  n++;
}

for (const d of DIRS) copy(d, d === "idea-lab" ? skipMarkdownInIdeaLab : undefined);
for (const t of TOOLS) copy("education/" + t);
for (const f of [...FILES, KEYFILE]) copy(f);

console.log(`  staged ${n} static paths into dist`);
